# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.trellisTest.com:587
mail_admin: admin@trellisTest.com
mail_hostname: trellisTest.com
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
